name: CI/CD Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # CRITICAL: Required for getCommitCount() and getCommitSha() functions to work!

      - name: Generate short SHA
        id: set-short-sha
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'

      # Programmatically generates a public testing keystore container right inside the execution worker
      - name: Generate Temporary Testing Keystore
        run: |
          keytool -genkeypair -v -keystore app/testing-debug.keystore -alias androiddebugkey -storepass android -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

       Silber step
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Compiles and injects the testing keys inline to satisfy project.property checks
      - name: Build with Gradle
        run: |
          ./gradlew assembleRelease \
            -PreleaseKeyStore="testing-debug.keystore" \
            -PreleaseKeyStorePassword="android" \
            -PreleaseKeyAlias="androiddebugkey" \
            -PreleaseKeyPassword="android"

      # NOTE: Artifact outputs updated from "-unsigned.apk" to "-release.apk" since they are now signed!
      - name: Upload app-arm64-v8a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvNext-arm64-v8a-release-signed-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Upload app-armeabi-v7a Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvNext-armeabi-v7a-release-signed-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Upload app-universal Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvNext-universal-release-signed-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-universal-release.apk

      - name: Upload app-x86 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvNext-x86-release-signed-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Upload app-x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mpvNext-x86_64-release-signed-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/release/app-x86_64-release.apk
